/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static interfaz.Login.adminPanel;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import rusia.Entidades.Usuario;
import rusia.Entidades.partido;
import rusia.Nucleo.claseRetorno;
import rusia.dataManager.manejadorPartidos;
import rusia.dataManager.manejadorUsuario;

/**
 *
 * @author user
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    manejadorPartidos mPartidos;
    Usuario usuarioLogeado;
    public Administrador() {
        initComponents();
        this.cargarXml();
        centrar();
        
        if (mUsuarios.obtenerUsuarios().isEmpty())
            CrearAdmin(); // Logearse como un usuario
        
        checkLogin();
    }

    private void checkLogin()
    {
        if (usuarioLogeado == null) {
            lusuario.setText("No logeado");
            new Login(this, this, true).setLocationRelativeTo(this);
        }
    }
    
    public void logearUsuario(Usuario usr)
    {
        this.usuarioLogeado = usr;
        lusuario.setText("Bienvenido " + usr.getNombre());
        if (usr.getRol().equals("Administrador"))
            busuarios.setVisible(true);
        else
            busuarios.setVisible(false);
            
    }
    
    manejadorUsuario mUsuarios = new manejadorUsuario();
    private void loginTest()
    {
        mUsuarios = new manejadorUsuario();
        Usuario usr = (Usuario) mUsuarios.checkLogin("admin", "admin").datos;
        logearUsuario(usr);
    }
    
    private void CrearAdmin()
    {
        mUsuarios = new manejadorUsuario();
        Usuario usr = new Usuario();
        usr.setNombre("admin");
        usr.setApellido("admin");
        usr.setNickname("admin");
        usr.setCorreo("admin");
        usr.setRol("Administrador");
        usr.setPassword("admin");
        mUsuarios.agregarUsuario(usr);
        logearUsuario(usr);
    }   
    
    public void centrar() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;

        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        this.setLocation(x, y);
    }
    
    public void cargarXml()
    {
        mPartidos = new manejadorPartidos();
        claseRetorno rx = mPartidos.cargarXml("F:\\DOCUMENTOS\\Documents\\NetBeansProjects\\Rusia 2\\xml.txt");
        System.out.println(rx.mensaje);
        
        DefaultListModel<partido> partidos = mPartidos.obtenerRegistros();
        for (int i=0; i<partidos.size()-1; i++)
            System.out.println("Face: " + partidos.elementAt(i).getFaseGrupo() + " - grupo: " + partidos.elementAt(i).getGrupo() + " - Clasifi: " + partidos.elementAt(i).getClasificacion());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInterno = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        busuarios = new javax.swing.JButton();
        bpartidos = new javax.swing.JButton();
        bpronostricos = new javax.swing.JButton();
        bpronostricos1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        lusuario = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiñiela Partidos");
        setPreferredSize(new java.awt.Dimension(1280, 720));

        panelInterno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelInternoLayout = new javax.swing.GroupLayout(panelInterno);
        panelInterno.setLayout(panelInternoLayout);
        panelInternoLayout.setHorizontalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1391, Short.MAX_VALUE)
        );
        panelInternoLayout.setVerticalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );

        getContentPane().add(panelInterno, java.awt.BorderLayout.CENTER);

        jToolBar1.setBackground(new java.awt.Color(139, 176, 248));
        jToolBar1.setFloatable(false);

        busuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iusuarios.png"))); // NOI18N
        busuarios.setText("Usuarios");
        busuarios.setFocusable(false);
        busuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        busuarios.setOpaque(false);
        busuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        busuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(busuarios);

        bpartidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ipartido2.png"))); // NOI18N
        bpartidos.setText("Partidos");
        bpartidos.setFocusable(false);
        bpartidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bpartidos.setOpaque(false);
        bpartidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bpartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpartidosActionPerformed(evt);
            }
        });
        jToolBar1.add(bpartidos);

        bpronostricos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ipronostico.png"))); // NOI18N
        bpronostricos.setText("Pronosticos");
        bpronostricos.setFocusable(false);
        bpronostricos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bpronostricos.setOpaque(false);
        bpronostricos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bpronostricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpronostricosActionPerformed(evt);
            }
        });
        jToolBar1.add(bpronostricos);

        bpronostricos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/pronostic.png"))); // NOI18N
        bpronostricos1.setText("Tabla de puntuaciones");
        bpronostricos1.setFocusable(false);
        bpronostricos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bpronostricos1.setOpaque(false);
        bpronostricos1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bpronostricos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpronostricos1ActionPerformed(evt);
            }
        });
        jToolBar1.add(bpronostricos1);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 36));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(574, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToolBar1.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMinimumSize(new java.awt.Dimension(260, 60));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(260, 60));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("Cerrar Sesion");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lusuario.setText("Bienvenido William");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setText("Editar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jToolBar1.add(jPanel2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private FUsuarios fusuarios;
    private void busuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busuariosActionPerformed
        if (fusuarios == null || !fusuarios.isVisible()){
            fusuarios = new FUsuarios(this);
            fusuarios.setResizable(true);
            fusuarios.setMaximizable(true);
            fusuarios.setIconifiable(true);
            fusuarios.setClosable(true);
            panelInterno.add(fusuarios);
        }
        fusuarios.setVisible(true);
        fusuarios.setFocusable(true);
        try {  fusuarios.setSelected(true);  } catch (Exception e) {}
    }//GEN-LAST:event_busuariosActionPerformed

    PartidosAdmin fpartidos;
    private void bpartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpartidosActionPerformed
        if (fpartidos == null || !fpartidos.isVisible()){
            fpartidos = new PartidosAdmin(this);
            fpartidos.setResizable(true);
            fpartidos.setMaximizable(true);
            fpartidos.setIconifiable(true);
            fpartidos.setClosable(true);
            panelInterno.add(fpartidos);
        }
        fpartidos.setVisible(true);
        fpartidos.setFocusable(true);
        try {  fpartidos.setSelected(true);  } catch (Exception e) {}
    }//GEN-LAST:event_bpartidosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        panelInterno.removeAll();
        panelInterno.updateUI();
        this.usuarioLogeado = null;
        this.checkLogin();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (usuarioLogeado != null)
            new JDEditarU(this,true, usuarioLogeado).setLocationRelativeTo(this);
        else
            JOptionPane.showMessageDialog(null, "Error ...");
        this.logearUsuario(usuarioLogeado);
    }//GEN-LAST:event_jButton3ActionPerformed

    PronosticosAdmin fpronosticos;
    private void bpronostricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpronostricosActionPerformed
        if (fpronosticos == null || !fpronosticos.isVisible()){
            fpronosticos = new PronosticosAdmin(this);
            fpronosticos.setResizable(true);
            fpronosticos.setMaximizable(true);
            fpronosticos.setIconifiable(true);
            fpronosticos.setClosable(true);
            panelInterno.add(fpronosticos);
        }
        fpronosticos.setVisible(true);
        fpronosticos.setFocusable(true);
        try {  fpronosticos.setSelected(true);  } catch (Exception e) {}
    }//GEN-LAST:event_bpronostricosActionPerformed

    public void agregarForm(JInternalFrame jif){ 
        panelInterno.add(jif);
    }
    
    Puntuaciones fpuntuaciones;
    private void bpronostricos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpronostricos1ActionPerformed
        if (fpuntuaciones == null || !fpuntuaciones.isVisible()){
            fpuntuaciones = new Puntuaciones(this, usuarioLogeado);
            fpuntuaciones.setResizable(true);
            fpuntuaciones.setMaximizable(true);
            fpuntuaciones.setIconifiable(true);
            fpuntuaciones.setClosable(true);
            panelInterno.add(fpuntuaciones);
        }
        fpuntuaciones.setVisible(true);
        fpuntuaciones.setFocusable(true);
        try {  fpuntuaciones.setSelected(true);  } catch (Exception e) {}
    }//GEN-LAST:event_bpronostricos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bpartidos;
    private javax.swing.JButton bpronostricos;
    private javax.swing.JButton bpronostricos1;
    private javax.swing.JButton busuarios;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lusuario;
    private javax.swing.JDesktopPane panelInterno;
    // End of variables declaration//GEN-END:variables
}
