/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static interfaz.Puntuaciones.SelectedId;
import java.awt.Point;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import rusia.Entidades.Usuario;
import rusia.dataManager.manejadorUsuario;

/**
 *
 * @author user
 */
public class FUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FUsuarios
     */
    private manejadorUsuario mUsuarios;
    private DefaultListModel usuarios;
    private JFrame padre;
    public FUsuarios(JFrame _padre) {
        initComponents();
        padre = _padre;
        mUsuarios = new manejadorUsuario();
        usuarios = mUsuarios.obtenerUsuarios();
        this.actualizarTabla();
    }

    public void actualizarTabla()
    {
        jtusuarios.setModel(mUsuarios.obtenerJTable());
        jtusuarios.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtusuarios = new javax.swing.JTable();
        cbFiltro = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();

        tbuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbuscarKeyTyped(evt);
            }
        });

        jLabel1.setText("Buscar por");
        jLabel1.setToolTipText("");

        jtusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtusuariosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtusuarios);

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Apellido", "Nickname", "Correo", "Privilegios" }));

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/addu.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.setMaximumSize(new java.awt.Dimension(120, 39));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 39));
        jButton1.setPreferredSize(new java.awt.Dimension(120, 39));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/editu.png"))); // NOI18N
        jButton2.setText("Editar");
        jButton2.setMaximumSize(new java.awt.Dimension(80, 39));
        jButton2.setMinimumSize(new java.awt.Dimension(80, 39));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ipronostico.png"))); // NOI18N
        jButton4.setText("Pronosticos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void tbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbuscarKeyTyped
        tbuscar.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e){
                String cadena = tbuscar.getText();
                tbuscar.setText(cadena);
                repaint();
                filtro();
            }
        });
        
        trsFiltro = new TableRowSorter(jtusuarios.getModel());
        jtusuarios.setRowSorter(trsFiltro);
    }//GEN-LAST:event_tbuscarKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new JDAgregar(this.padre,true,this).setLocationRelativeTo(this.padre);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.EditarUsuario();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EditarUsuario()
    {
        Usuario usr = (Usuario)mUsuarios.buscarPorID(SelectedId).datos;
        if (usr != null)
            new JDEditarU(this.padre,true, usr).setLocationRelativeTo(this);
        else
            JOptionPane.showMessageDialog(null, "Error no ha seleccionado ningun usuario.");
        
        this.actualizarTabla();
    }
    
    String SelectedId = "";
    private void jtusuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtusuariosMousePressed
        JTable tabla =(JTable) evt.getSource();
        Point punto = evt.getPoint();
        int row = tabla.rowAtPoint(punto);
        
        SelectedId = (String)tabla.getValueAt(row, 0);
        if (evt.getClickCount() == 2 && tabla.getSelectedRow() != -1)
            this.EditarUsuario();
    }//GEN-LAST:event_jtusuariosMousePressed

    PronosticosAdmin pronosticoAdmin;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Administrador adminPanel = (Administrador) padre;
        manejadorUsuario mUsuario = new manejadorUsuario();
        Usuario usr = (Usuario) mUsuario.buscarPorID(SelectedId).datos;
        if (pronosticoAdmin == null || !pronosticoAdmin.isVisible()) // PARA NO ABRIR VARIOS FORMULARIOS DE PRONOSTICOS
        {
            pronosticoAdmin = new PronosticosAdmin(adminPanel);
            pronosticoAdmin.setResizable(true);
            pronosticoAdmin.setMaximizable(true);
            pronosticoAdmin.setIconifiable(true);
            pronosticoAdmin.setClosable(true);
            adminPanel.agregarForm(pronosticoAdmin);
        }
        
        pronosticoAdmin.filtrarporNickname(usr.getNickname());
        pronosticoAdmin.setVisible(true);
        pronosticoAdmin.setFocusable(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private TableRowSorter trsFiltro;
    private void filtro()
    {
        int colBuscar = 0;
        colBuscar = cbFiltro.getSelectedIndex()+1;
        if (cbFiltro.getSelectedItem() == "Privilegios")
            colBuscar = 8;
        trsFiltro.setRowFilter(RowFilter.regexFilter(tbuscar.getText(), colBuscar));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable jtusuarios;
    private javax.swing.JTextField tbuscar;
    // End of variables declaration//GEN-END:variables
}
