/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Point;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import rusia.Entidades.partido;
import rusia.dataManager.manejadorPartidos;
import rusia.dataManager.manejadorPronosticos;
import rusia.dataManager.manejadorUsuario;

/**
 *
 * @author Aura Marina Choxon
 */
public class PartidosAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form PartidosAdmin
     */
    private manejadorPartidos mPartidos;
    private DefaultListModel partidos;
    public Administrador padre;
    public PartidosAdmin(Administrador _padre) {
        initComponents();
        padre = _padre;
        mPartidos = new manejadorPartidos();
        partidos = mPartidos.obtenerRegistros();
        this.actualizarTabla();
        
        lgrupos.setVisible(false);
        cbgrupos.setVisible(false);
        
        if (_padre.usuarioLogeado.getRol().equals("Administrador"))
            bpronosticar.setVisible(false);
        else
            bmarcador.setVisible(false);
    }

    public void actualizarTabla()
    { 
        jtpartidos.setModel(mPartidos.obtenerJTable());
        jtpartidos.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtpartidos = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        bmarcador = new javax.swing.JButton();
        bpronosticar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbgrupos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lgrupos = new javax.swing.JLabel();
        cbclasificacion = new javax.swing.JComboBox<>();

        setTitle("Partidos");

        jtpartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtpartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtpartidosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtpartidos);

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iinfo2.png"))); // NOI18N
        jButton1.setText("Informacion");
        jButton1.setMaximumSize(new java.awt.Dimension(120, 39));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 39));
        jButton1.setPreferredSize(new java.awt.Dimension(120, 39));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        bmarcador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ipuntuar.png"))); // NOI18N
        bmarcador.setText("Ingresar Marcador");
        bmarcador.setMaximumSize(new java.awt.Dimension(150, 39));
        bmarcador.setMinimumSize(new java.awt.Dimension(150, 39));
        bmarcador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmarcadorActionPerformed(evt);
            }
        });
        jToolBar1.add(bmarcador);

        bpronosticar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ipronostico.png"))); // NOI18N
        bpronosticar.setText("Pronosticar");
        bpronosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpronosticarActionPerformed(evt);
            }
        });
        jToolBar1.add(bpronosticar);

        cbgrupos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ver Todos", "GrupoA", "GrupoB", "GrupoC", "GrupoD", "GrupoE", "GrupoF", "GrupoG", "GrupoH" }));
        cbgrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgruposActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar por");

        jLabel2.setText("Clasificacion");

        lgrupos.setText("Grupos");

        cbclasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ver Todos", "FaseGrupos", "Octavos", "Cuartos", "Semifinales", "TercerPuesto", "Final" }));
        cbclasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbclasificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbclasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lgrupos)
                    .addComponent(cbgrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lgrupos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbclasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbgrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String SelectedId;
    private void jtpartidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpartidosMousePressed
        JTable tabla =(JTable) evt.getSource();
        Point punto = evt.getPoint();
        int row = tabla.rowAtPoint(punto);

        SelectedId = (String)tabla.getValueAt(row, 0);
        if (evt.getClickCount() == 2 && tabla.getSelectedRow() != -1)
        mostrarInfo("info");
    }//GEN-LAST:event_jtpartidosMousePressed

    public void mostrarInfo(String boton) { 
        manejadorPronosticos mPronostico = new manejadorPronosticos();
        partido _partido = new partido();
        _partido = (partido) mPartidos.buscarPorID(SelectedId).datos;
        _partido.setFaseGrupo(boton);
        
        if (!boton.equals("info") ){ 
            if (mPronostico.existePronostico(_partido, padre.usuarioLogeado) ){
                JOptionPane.showMessageDialog(this, "No puede volver a pronosticarlo, solo editar el pronostico ya hecho.");
                return;
            }
                
            
            if (!_partido.isFinalizado())
                new partidoInfo(this.padre,true,_partido, padre.usuarioLogeado).setVisible(true);
            else
                JOptionPane.showMessageDialog(this, "El partido ya se a jugado, no puedo pronosticar/editar un partido que ya se jugo.");
        }
        else
            new partidoInfo(this.padre,true,_partido, padre.usuarioLogeado).setVisible(true);
    }
    
    private TableRowSorter trsFiltro;
    private void filtro()
    {
        
        int colBuscar = 0;
        String tb = "";
        if (!cbclasificacion.getSelectedItem().equals("FaseGrupos") || cbgrupos.getSelectedItem().equals("Ver Todos")){
            colBuscar = 1;
            tb = cbclasificacion.getSelectedItem().toString();
        }
        else{
            colBuscar = 3;
            tb = cbgrupos.getSelectedItem().toString();
        }
        
        //JOptionPane.showMessageDialog(null, tb);
        trsFiltro.setRowFilter(RowFilter.regexFilter(tb, colBuscar));
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        mostrarInfo("info");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bmarcadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmarcadorActionPerformed
        mostrarInfo("admin");
    }//GEN-LAST:event_bmarcadorActionPerformed

    private void cbclasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbclasificacionActionPerformed
            lgrupos.setVisible(cbclasificacion.getSelectedItem().equals("FaseGrupos"));
            cbgrupos.setVisible(cbclasificacion.getSelectedItem().equals("FaseGrupos"));
            trsFiltro = new TableRowSorter(jtpartidos.getModel());
            jtpartidos.setRowSorter(trsFiltro);
            
            if (!cbclasificacion.getSelectedItem().equals("Ver Todos"))
                filtro();
                
    }//GEN-LAST:event_cbclasificacionActionPerformed

    private void cbgruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgruposActionPerformed
        filtro();
    }//GEN-LAST:event_cbgruposActionPerformed

    private void bpronosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpronosticarActionPerformed
        mostrarInfo("usuario");
    }//GEN-LAST:event_bpronosticarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmarcador;
    private javax.swing.JButton bpronosticar;
    private javax.swing.JComboBox<String> cbclasificacion;
    private javax.swing.JComboBox<String> cbgrupos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable jtpartidos;
    private javax.swing.JLabel lgrupos;
    // End of variables declaration//GEN-END:variables
}
